export enum HTTP_MESSAGE {
  OK = 'OK',
  SUCCESS = 'Success',
  FAILED = 'Failed',
  NOT_FOUND = 'Not Found',
  UNAUTHORIZED = 'Unauthorized',
  FORBIDDEN = 'Forbidden',
  BAD_REQUEST = 'Bad Request',
  INTERNAL_SERVER_ERROR = 'Internal Server Error',
  UPDATED = 'Updated Successfully',
  CREATED = 'Created Successfully',
  DELETED = 'Deleted Successfully',
  VERIFIED = 'Verified Successfully',
  ECONNREFUSED = 'Connection Refused',
}
